### ISSUE TITLE
how can i install this manually?

### ISSUE THREAD

**Issue by sunshe35** [nikitakit/xdbg#1]
this doesn't have a setup.py.
So that i can't use pip to install it.
I download this packages ,and copyt it to "d:\Anaconda\Lib\",but when i open my ipython ,i cant import xdbg.
i just set it to the environment path now time,and i don't know weather it works.

**Comment by nikitakit** [comment]
I just added a `setup.py` to the repo. You should be able to use it to install this package.

**Comment by nikitakit** [comment]
Closing this issue, since a `setup.py` has been added and no problems using it have been reported.
